language: ruby
rvm:
  - 2.6.3

branches:
  only:
    - source

cache: bundler

install:
  - gem install jekyll bundler
  - git config --global user.email "mail@sujanpoudel.me"
  - git config --global user.name "psuzn"


