# Site
name: "Sujan Poudel"
author: "Sujan Poudel"
picture: "https://www.gravatar.com/avatar/0ae70015cd23df3f9e5bae80c8fb394d?s=512"
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
google_analytics: "UA-142516091-2"
disqus: "demowebsite"
mailchimp-list: "https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b"
include: ["_pages"]
permalink: /:title/
type: "personal blog"

me:
  name: Sujan Poudel
  display_name: psuzn
  gravatar: 0ae70015cd23df3f9e5bae80c8fb394d
  email: mail@sujanpoudel.me
  web: https://sujanpoudel.me
  github: https://github.com/psuzn
  twitter: https://twitter.com/psuzn
  linkedin: https://www.linkedin.com/in/psuzn/
  stackoverflow: https://stackoverflow.com/users/6770321/sujan-poudel
  blog_repo: https://github.com/psuzn


seo:
 name: "Sujan Poudel"
 type: "Personal Blog"

twitter:
  username: psuzn
  card: summary

  # Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
